name: Design9 Imagination
favicon: null
layout_spectrum: 0
typography_spectrum: 0.49417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#7651a1'
    - '#432c62'
    - '#9f9f9f'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
